language: go

go:
    - 1.4

before_install:
    - go get github.com/mattn/goveralls
    - go get github.com/bradfitz/goimports
    - go get github.com/golang/lint/golint

script:
    - ./travisbuild.sh

after_script:
    - $HOME/gopath/bin/goveralls -coverprofile=profile.cov -service=travis-ci
