language: haskell

ghc: 7.8

before_install:
    - cabal install happy
    - cabal install alex
    - cabal install --only-dependencies --enable-tests

script:
    - cabal configure --enable-tests --enable-library-coverage && cabal build && cabal test

after_script:
    - cabal install hpc-coveralls
    - hpc-coveralls tests
